Propogate exit code as function argument
Remove script_exit_code variable propogating the exit code as a function
argument instead.

Signed-off-by: Mark Grant <m.grant.prg@gmail.com>

diff --git a/src/prg/bash/dnsmasq-postrotate.sh.in b/src/prg/bash/dnsmasq-postrotate.sh.in
--- a/src/prg/bash/dnsmasq-postrotate.sh.in
+++ b/src/prg/bash/dnsmasq-postrotate.sh.in
@@ -71,13 +71,15 @@
 #				location.				#
 # 21/12/2018	MG	1.0.5	Use more standard printf instead of	#
 #				echo.					#
+#				Remove script_exit_code variable 	#
+#				propogating the exit code as a function	#
+#				argument instead.			#
 #									#
 #########################################################################
 
 #########################
 # Script-wide variables #
 #########################
-script_exit_code=0
 readonly outputprefix="$(basename $0):"
 readonly version="1.0.4"			# script version
 readonly packageversion=@pkgversion@		# package version
@@ -97,6 +99,8 @@ verbose=false
 #############
 
 # -h --help output.
+# No parameters
+# No return value
 usage ()
 {
 cat << EOF
@@ -115,9 +119,14 @@ Usage is $0 [options]
 EOF
 }
 
-# If $3 == 0 always output $1 to stdout or stderr depending on $2. If $3 == 1
-# then output only if $verbose is true. If $3 == 2 then output only if $trace is
-# true.
+# Standard function to emit messages depending on various parameters.
+# Parameters -	$1 What:-	The message to emit.
+#		$2 Where:-	stdout == 0
+#				stderr == 1
+#		$3 When:-	$3 == 0, Always.
+#				$3 == 1, Output only if $verbose is true.
+#				$3 == 2, Output only if $trace is true.
+# No return value.
 output()
 {
 	if [[ $3 = 0 ]] || ([[ $3 = 1 ]] && $verbose) \
@@ -132,35 +141,39 @@ output()
 	fi
 }
 
-# Standard function to test command error ($1 is $?) and exit if non-zero
+# Standard function to test command error and exit if non-zero.
+# Parameters - 	$1 is the exit code, (normally $? from the preceeding command).
+# No return value.
 std_cmd_err_handler()
 {
 	if [ $1 != 0 ]; then
-		script_exit_code=$1
-		script_exit
+		script_exit $1
 	fi
 }
 
-# Standard function to tidy up and return exit code
+# Standard function to tidy up and return exit code.
+# Parameters - 	$1 is the exit code.
+# No return value.
 script_exit()
 {
-	exit $script_exit_code
+	exit $1
 }
 
-# Standard trap exit function
+# Standard trap exit function.
+# No parameters.
+# No return value.
 trap_exit()
 {
-script_exit_code=1
 output "Script terminating due to trap received." 1 0
-script_exit
+script_exit 1
 }
 
-# Setup trap
+# Setup trap.
 trap trap_exit SIGHUP SIGINT SIGTERM
 
 # Process command line arguments with GNU getopt.
-# Parameter - command line
-# No return value
+# Parameters -	$1 is the command line.
+# No return value.
 proc_CL()
 {
 	local GETOPTTEMP
@@ -180,8 +193,7 @@ proc_CL()
 		-h|--help)
 			usage
 			shift
-			script_exit_code=0
-			script_exit
+			script_exit 0
 			;;
 		-p|--post-rotate)
 			postrotate=true
@@ -204,29 +216,26 @@ proc_CL()
 			printf "%s Script version %s\n" $0 $version
 			printf "%s Package version %s\n" $0 $packageversion
 			shift
-			script_exit_code=0
-			script_exit
+			script_exit 0
 			;;
 		--)	shift
 			break
 			;;
-		*)	script_exit_code=1
-			output "Internal error." 1 0
-			script_exit
+		*)	output "Internal error." 1 0
+			script_exit 1
 			;;
 		esac
 	done
 
 	# Script does not accept other arguments.
 	if [ $# -gt 0 ]; then
-		script_exit_code=1
 		output "Invalid argument." 1 0
-		script_exit
+		script_exit 1
 	fi
 }
 
 # Process a conf-dir parameter - a directory and masks.
-# $1 - A conf-dir parameter.
+# Parameters -	$1 is a conf-dir parameter.
 # No return value.
 proc_conf_dir ()
 {
@@ -264,7 +273,7 @@ proc_conf_dir ()
 }
 
 # Parse the command line only for the parameters of interest.
-# $@ - The dnsmasq command line.
+# Parameters -	$@ is the dnsmasq command line.
 # No return value.
 cmd_line_parse()
 {
@@ -320,7 +329,7 @@ cmd_line_parse()
 }
 
 # Process a conf file.
-# $1 - A conf-file parameter (A config filename).
+# Parameters -	$1 is a conf-file parameter (A config filename).
 # No return value.
 proc_conf_file()
 {
@@ -386,7 +395,7 @@ proc_conf_file()
 }
 
 # Process the aggregated list of conf files from next_conf_file_list.
-# $@ - The list of conf-files to process.
+# Parameters -	$@ is the list of conf-files to process.
 # No return value.
 proc_conf_file_list()
 {
@@ -426,8 +435,7 @@ get_oldloglocation()
 
 	if [[ ! -f $logrotatefile ]]; then
 		output "Log rotate file $logrotatefile does not exist." 1 0
-		script_exit_code=1
-		script_exit
+		script_exit 1
 	fi
 
 	exec 4<$logrotatefile
@@ -544,8 +552,7 @@ setup_logrotate()
 {
 	if [[ ! -f $logrotatefile ]]; then
 		output "Log rotate file $logrotatefile does not exist." 1 0
-		script_exit_code=1
-		script_exit
+		script_exit 1
 	fi
 
 	# Copy up to first live line.
@@ -588,15 +595,13 @@ if $setup ; then
 fi
 
 if [[ ! $pidnum ]]; then
-	script_exit_code=0
 	output "dnsmasq daemon not running." 0 1
-	script_exit
+	script_exit 0
 fi
 
 if $postrotate ; then
 	signal_dnsmasq
 fi
 
-script_exit_code=0
-script_exit
+script_exit 0
 
