bash: Move script_exit() before it is used
Signed-off-by: Mark Grant <m.grant.prg@gmail.com>

diff --git a/src/prg/bash/dnsmasq-postrotate.sh.in b/src/prg/bash/dnsmasq-postrotate.sh.in
--- a/src/prg/bash/dnsmasq-postrotate.sh.in
+++ b/src/prg/bash/dnsmasq-postrotate.sh.in
@@ -103,6 +103,7 @@
 #				Replace #! env bash with absolute path	#
 #				via configure.				#
 # 10/08/2019	MG	1.0.7	Correct getopt CL for proper quoting.	#
+# 11/10/2019	MG	1.0.8	Move script_exit() before it is used.	#
 #									#
 #########################################################################
 
@@ -110,7 +111,7 @@
 # Script-wide variables #
 #########################
 readonly outputprefix="$(basename $0):"
-readonly version=1.0.7				# script version
+readonly version=1.0.8				# script version
 readonly packageversion=@pkgversion@		# package version
 
 readonly logrotatefile="@sysconfdir@/logrotate.d/dnsmasq"
@@ -170,6 +171,14 @@ output()
 	fi
 }
 
+# Standard function to tidy up and return exit code.
+# Parameters - 	$1 is the exit code.
+# No return value.
+script_exit()
+{
+	exit $1
+}
+
 # Standard function to test command error and exit if non-zero.
 # Parameters - 	$1 is the exit code, (normally $? from the preceeding command).
 # No return value.
@@ -178,14 +187,6 @@ std_cmd_err_handler()
 	if (( $1 )); then
 		script_exit $1
 	fi
-}
-
-# Standard function to tidy up and return exit code.
-# Parameters - 	$1 is the exit code.
-# No return value.
-script_exit()
-{
-	exit $1
 }
 
 # Standard trap exit function.
